### ISSUE TITLE
Try exporting a file by entering only entering start date

### ISSUE THREAD

**Issue by Siqbal1234** [merrecdarkin/Wil-Project-AEMO-CSV-Efficient-Reading-Sorting-and-Export-#17]
1. Description:
App crashes when clicking export button after selecting the correct  CSV files and just entering the start date with correct and incorrect format

2. Steps to reproduce:
2.1. Open app
2.2. Select the proper CSV file 
2.3. Enter the start date with proper format or in wrong format  that is present in selected CSV files 
2.4. Click the export button
2.5 App crashed 

3. Error log: 
4. 
![image](https://user-images.githubusercontent.com/113232225/189637631-418af966-3fb9-471e-a555-bdc4158eda1f.png)

5. Expected results:

When correct format is entered all the data related to the input should export.
When incorrect format is entered, Error handling and visual output to notify incorrect date format is entered.

**Comment by larryh12** [comment]
@Siqbal1234 Two different issues combined.

1. > When correct format is entered all the data related to the input should export. >

2. > When incorrect format is entered, Error handling and visual output to notify incorrect date format is entered. >

**Comment by larryh12** [comment]
#17 will be now reserved to resolve the first scenario, exporting all data with only date range filter.

This requires a conditional check when both `DUIDset` and `BIDTYPEset` was not passed (passed as empty) to `loadCSV` function, by default both of them are assigned as `True`, so the query becomes `True and True`, thus throws exceptions.

**Comment by larryh12** [comment]
#19 will be now reserved to resolve the second scenario, wrong date input format.

> When incorrect format is entered, Error handling and visual output to notify incorrect date format is entered.
