### ISSUE TITLE
Not able to export file by entering special characters in the search field

### ISSUE THREAD

**Issue by Siqbal1234** [merrecdarkin/Wil-Project-AEMO-CSV-Efficient-Reading-Sorting-and-Export-#18]
1. Description:
App crashes when trying to export a file by entering DUID with special character in the name.

2. Steps to reproduce:
2.1. Created an own CSV file and added a special character in DUID.
2.2. Selected the folder with a CSV file in it 
2.3. Export the file after entering the DUID name with special character in it in the DUID feild
2.4. Crashed
3. Error log:
![image](https://user-images.githubusercontent.com/113232225/189641107-d5acb82c-77a5-455a-bb10-e8341f3ea716.png)
4. Expected results:
A file should be exported as the entered DUID was present in the selected CSV file

**Comment by larryh12** [comment]
@Siqbal1234 Could you please give an example on what was the special character did you use in your test case? If possible, please provide the exact text that you input in the app.

**Comment by larryh12** [comment]
Tester modified csv in Excel and corrupted the csv format. Issue closed for now.
