### ISSUE TITLE
Entered BIDTYPE in the DUID field

### ISSUE THREAD

**Issue by Siqbal1234** [merrecdarkin/Wil-Project-AEMO-CSV-Efficient-Reading-Sorting-and-Export-#25]
Description:
Tried exporting a file by entering BIDTYPE in the DUID field. 

Steps to reproduce:
2.1. Selected the folder with CSV files in it.
2.2. Entered BIDTYPE in the DUID field. 
2.3. App crashed when clicked the export button

Error log:
![image](https://user-images.githubusercontent.com/113232225/190841756-7956b8e1-04e9-47c1-aeb4-31134b4f962b.png)
Expected results:
An error message to notify user to enter correct type of data in the feild

**Comment by larryh12** [comment]
Dup #24
