### ISSUE TITLE
Exporting a file by selecting the CSV files but leaving all the other required fields blank,

### ISSUE THREAD

**Issue by Siqbal1234** [merrecdarkin/Wil-Project-AEMO-CSV-Efficient-Reading-Sorting-and-Export-#26]
Description:
Tried exporting a file by selecting the CSV files but leaving all the other required fields blank,

Steps to reproduce:
2.1. Selected the folder with CSV files in it.
2.2. Clicked the export button

Error log:
![image](https://user-images.githubusercontent.com/113232225/190842214-c612a6d4-1932-4c2c-aad2-42ed120c6692.png)

Expected results:
An error message to notify user to enter required data in the fields.

**Comment by larryh12** [comment]
Judging by the log, everything seems to run without problems. Are you getting your output.xlsx file afterwards? A few others have tested and confirmed that it worked for them without any issues. @Siqbal1234

**Comment by larryh12** [comment]
Could not replicate.
No response from tester.
Closed for now.
