### ISSUE TITLE
Exporting a CSV file without selecting an Output Folder.

### ISSUE THREAD

**Issue by Siqbal1234** [merrecdarkin/Wil-Project-AEMO-CSV-Efficient-Reading-Sorting-and-Export-#31]
Description:
Tried exporting a CSV file without selecting an Output Folder.

Steps to reproduce:
2.1. Selected the folder with CSV files in it.
2.2. Entered DUID in the DUID field 
2.3. Click the export button
2.4 Nothing exported

Error log:
![image](https://user-images.githubusercontent.com/113232225/192081551-bfcf4d4a-aa5f-4781-ad45-54cb3eb6843a.png)

Expected results:
An error message to notify user to select an output folder.

**Comment by larryh12** [comment]
1. Have you tried replicate multiple times and confirmed that this is a persistent issue?

2. By default without selecting output folder and/or specify export name, the app will export a file called “output.xlsx” in the same folder where you run your exe. Could you verify that there’s no such file exist?

**Comment by larryh12** [comment]
The app did export `output.xlsx` to current path.
Tester just did not check for it.
